### ISSUE TITLE
Upgrade mongoose due to potential security vulnerability

### ISSUE THREAD

**Issue by lisette-espin** [gesiscss/UnSexistifyIt#2]
Hi, 
Could you please upgrade mongoose from your "package-lock.json" file?

Here more info:
https://github.com/gesiscss/UnSexistifyIt/network/alert/package-lock.json/mongoose/open

Thanks!

**Comment by lisette-espin** [comment]
Could you please check the fix for this vulnerability?
I'm still getting the alert.
Thanks!

**Comment by aliaghelmaleki** [comment]
following packages got updated to:
+ npm@6.13.4
+ mongoose@5.8.1
+ helmet@3.21.2

Cheers!

**Comment by lisette-espin** [comment]
Hi,
I have accepted the 2 pull requests to automatically fix the vulnerabilities on:
- mongoose from 5.2.12 to 5.7.5
- npm from 6.10.2 to 6.13.4

Please @AliAghel double check that everything is correct.
thanks!
