### ISSUE TITLE
Security vulnerability

### ISSUE THREAD

**Issue by lisette-espin** [gesiscss/UnSexistifyIt#4]
Hi @AliAghel and @hide-ous ,
Could you please take a look into the **https-proxy-agent** vulnerability and fix it?
That would be nice.
Thanks

https://github.com/gesiscss/UnSexistifyIt/network/alert/package-lock.json/https-proxy-agent/open

**Comment by lisette-espin** [comment]
could you please also check:
https://github.com/gesiscss/UnSexistifyIt/network/alert/package-lock.json/kind-of/open

thanks

**Comment by gesis-css** [comment]
Dear @hide-ous  and @AliAghel 
Could you please take care of the new security vulnerabilities found this week in this repo?
https://github.com/gesiscss/UnSexistifyIt/network/alerts

Thanks!

**Comment by hide-ous** [comment]
thanks for the notification, fixed in bc73529
